### ISSUE TITLE
Refresh UI

### ISSUE THREAD

**Issue by mounirlamouri** [mounirlamouri/manifest-validator#11]
@beaufortfrancois seems interested to work on it. I have uploaded my WIP ui code. He may or may not reuse it.

**Comment by mounirlamouri** [comment]
https://github.com/mounirlamouri/manifest-validator/tree/new-ui

**Comment by beaufortfrancois** [comment]
Addressed partially by https://github.com/mounirlamouri/manifest-validator/pull/19

**Comment by nhoizey** [comment]
It might be nice to have the "Success: Manifest is valid!" message sooner in the flow, because it is bellow the fold even on my MacBook 13"

**Comment by beaufortfrancois** [comment]
Can you share a screenshot?
It should autoscroll to the message: https://manifest-validator.appspot.com/

**Comment by nhoizey** [comment]
Actualy it does (now) scroll, but to far… ;-)

![2016-03-29 at 15 25](https://cloud.githubusercontent.com/assets/78213/14109500/a2d211de-f5c2-11e5-8eae-acb21748b26c.png)

I'm using Firefox stable on latest Mac OS X.
