### ISSUE TITLE
Marcos' manifest parser is more awesome...

### ISSUE THREAD

**Issue by marcoscaceres** [mounirlamouri/manifest-validator#13]
Just sayin'
https://github.com/mozilla/gecko-dev/blob/master/dom/manifest/ManifestProcessor.jsm

Could generalize it to use in browser and Node :wink:

**Comment by surma** [comment]
> Marcos' manifest parser is more awesome

Could you elaborate what features you are missing with our version? We are also working on making this one available in a node module in #8.

**Comment by marcoscaceres** [comment]
That was joke intended from @mounirlamouri :blush:. It would be nice have a single, modern (ES6), code base for us to hack on tho.
