### ISSUE TITLE
Support passing in website-url via GET

### ISSUE THREAD

**Issue by ithinkihaveacat** [mounirlamouri/manifest-validator#36]
To quickly demonstrate of problems, it would be useful if the validator could be used via URLs like:

https://manifest-validator.appspot.com/?website-url=https://example.com

**Comment by beaufortfrancois** [comment]
You can already do this with `https://manifest-validator.appspot.com/#https://example.com`.
Note it may fail because of https://github.com/mounirlamouri/manifest-validator/pull/37.
