### ISSUE TITLE
a user should be able to paste a link to their website

### ISSUE THREAD

**Issue by samccone** [mounirlamouri/manifest-validator#4]
Instead of having to paste the entire json :)

**Comment by dandv** [comment]
This doesn't work for https://mfpwa2.firebaseapp.com/manifest.json:

![image](https://cloud.githubusercontent.com/assets/33569/13441537/8a968a04-dfac-11e5-9a25-998efe8dd96e.png)

**Comment by beaufortfrancois** [comment]
It does when you enter Website URL (https://mfpwa2.firebaseapp.com) not manifest.json URL ;)

**Comment by samccone** [comment]
@beaufortfrancois perhaps we should handle both :)

**Comment by dandv** [comment]
Yeah, I totally misread "Website" :) Handling both would help those in a similarly distracted state.

**Comment by beaufortfrancois** [comment]
@mounirlamouri WDYT?

On one hand, I agree it could be practical but on the other hand, we want to make sure your manifest file is indeed discoverable from your website URL.

Should we make the error message better to avoid confusion?
